# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Projeto-Taludes\\betsabe\\popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 338)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 541, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_mapa = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_mapa.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_mapa.setObjectName("gridLayout_mapa")
        self.botao_regiao1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao1.setText("")
        self.botao_regiao1.setObjectName("botao_regiao1")
        self.gridLayout_mapa.addWidget(self.botao_regiao1, 0, 0, 1, 1)
        self.botao_regiao2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao2.setText("")
        self.botao_regiao2.setObjectName("botao_regiao2")
        self.gridLayout_mapa.addWidget(self.botao_regiao2, 0, 1, 1, 1)
        self.botao_regiao3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao3.setText("")
        self.botao_regiao3.setObjectName("botao_regiao3")
        self.gridLayout_mapa.addWidget(self.botao_regiao3, 0, 2, 1, 1)
        self.botao_regiao4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao4.setText("")
        self.botao_regiao4.setObjectName("botao_regiao4")
        self.gridLayout_mapa.addWidget(self.botao_regiao4, 0, 3, 1, 1)
        self.botao_regiao5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao5.setText("")
        self.botao_regiao5.setObjectName("botao_regiao5")
        self.gridLayout_mapa.addWidget(self.botao_regiao5, 0, 4, 1, 1)
        self.botao_regiao6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao6.setText("")
        self.botao_regiao6.setObjectName("botao_regiao6")
        self.gridLayout_mapa.addWidget(self.botao_regiao6, 1, 0, 1, 1)
        self.botao_regiao8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao8.setText("")
        self.botao_regiao8.setObjectName("botao_regiao8")
        self.gridLayout_mapa.addWidget(self.botao_regiao8, 1, 2, 1, 1)
        self.botao_regiao12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao12.setText("")
        self.botao_regiao12.setObjectName("botao_regiao12")
        self.gridLayout_mapa.addWidget(self.botao_regiao12, 2, 1, 1, 1)
        self.botao_regiao9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao9.setText("")
        self.botao_regiao9.setObjectName("botao_regiao9")
        self.gridLayout_mapa.addWidget(self.botao_regiao9, 1, 3, 1, 1)
        self.botao_regiao11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao11.setText("")
        self.botao_regiao11.setObjectName("botao_regiao11")
        self.gridLayout_mapa.addWidget(self.botao_regiao11, 2, 0, 1, 1)
        self.botao_regiao14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao14.setText("")
        self.botao_regiao14.setObjectName("botao_regiao14")
        self.gridLayout_mapa.addWidget(self.botao_regiao14, 2, 3, 1, 1)
        self.botao_regiao7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao7.setText("")
        self.botao_regiao7.setObjectName("botao_regiao7")
        self.gridLayout_mapa.addWidget(self.botao_regiao7, 1, 1, 1, 1)
        self.botao_regiao15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao15.setText("")
        self.botao_regiao15.setObjectName("botao_regiao15")
        self.gridLayout_mapa.addWidget(self.botao_regiao15, 2, 4, 1, 1)
        self.botao_regiao13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao13.setText("")
        self.botao_regiao13.setObjectName("botao_regiao13")
        self.gridLayout_mapa.addWidget(self.botao_regiao13, 2, 2, 1, 1)
        self.botao_regiao10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao_regiao10.setText("")
        self.botao_regiao10.setObjectName("botao_regiao10")
        self.gridLayout_mapa.addWidget(self.botao_regiao10, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
